### ISSUE TITLE
'kind' of undefined

### ISSUE THREAD

**Issue by owlauch** [inorganik/ngx-countUp#38]
```
[ ] Bug
[ x ] Build issue
[ ] Feature request
```

#### Version info 

ngular CLI: 8.1.1
Node: 10.16.3
OS: win32 x64
Angular: 8.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.1.1
@ngtools/webpack                  8.0.6
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
```
Angular:
Angular CLI:
ngx-countup: 
```

#### Description

ng build --configuration="production" returns:
ERROR in ./node_modules/ngx-countup/fesm5/ngx-countup.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16514:30)
    at Object.forEachChild (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16740:24)
    at checkNodeForDecorators (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16635:21)
    at checkNodeForDecorators (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16692:24)
    at checkNodeForDecorators (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16703:24)
    at checkNodeForDecorators (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16599:21)
    at Object.forEachChild (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16635:21)
    at checkNodeForDecorators (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16692:24)
    at checkNodeForDecorators (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16703:24)
    at checkNodeForDecorators (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\software\estavel\hawker-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16599:21)

**Comment by lsvt-tate** [comment]
My build is also returning the same error.

**Comment by inorganik** [comment]
I don't believe this is related to ngx-countup. I created a fresh project with v8.3.9 of the CLI, node 10.16.3, and installed ngx-countup. I implemented it and tested it with ng serve, and it worked. I ran `ng build --prod` and it compiled with no errors. 

I did find this issue thread on @angular/cli: https://github.com/angular/angular-cli/issues/13172

After browsing messages in that thread, it seems like you should try the usual stuff - 
- blow away node_modules and reinstall
- update angular packages
