### ISSUE TITLE
NG build --prod failing due to "cannot read 'kind' of undefined"

### ISSUE THREAD

**Issue by cjrutherford** [inorganik/ngx-countUp#42]
```
[ ] Bug
[X ] Build issue
[ ] Feature request
```

#### Version info 

```
Angular: 7.0.0
Angular CLI: 9.x
ngx-countup: ^7.3.0
```

#### Description
I'm currently trying to build my app and because I'm using NGX-countup, I have issues with building and get the following output. I have little insight into what the dependancies for ngx-countup are, but I would like to help get this fixed if possible. (inherited project...) Currently only happening when using the `--prod` flag with `ng build`

```
ERROR in ./node_modules/ngx-countup/fesm5/ngx-countup.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/Users/christopherrutherford/dev/mhp-proper/ui/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/Users/christopherrutherford/dev/mhp-proper/ui/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/Users/christopherrutherford/dev/mhp-proper/ui/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16144:30)
    at Object.forEachChild (/Users/christopherrutherford/dev/mhp-proper/ui/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16370:24)
    at checkNodeForDecorators (/Users/christopherrutherford/dev/mhp-proper/ui/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/christopherrutherford/dev/mhp-proper/ui/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
    at Object.forEachChild (/Users/christopherrutherford/dev/mhp-proper/ui/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16265:21)
    at checkNodeForDecorators (/Users/christopherrutherford/dev/mhp-proper/ui/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/christopherrutherford/dev/mhp-proper/ui/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
    at Object.forEachChild (/Users/christopherrutherford/dev/mhp-proper/ui/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16322:24)
    at checkNodeForDecorators (/Users/christopherrutherford/dev/mhp-proper/ui/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/christopherrutherford/dev/mhp-proper/ui/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
    at Object.forEachChild (/Users/christopherrutherford/dev/mhp-proper/ui/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16333:24)
    at checkNodeForDecorators (/Users/christopherrutherford/dev/mhp-proper/ui/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/christopherrutherford/dev/mhp-proper/ui/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
    at Object.forEachChild (/Users/christopherrutherford/dev/mhp-proper/ui/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16229:21)
```

**Comment by inorganik** [comment]
This has already been posted as an issue, #38 - I don't believe it's related to ngx-countUp.

See also: https://stackoverflow.com/questions/57891605/angular-cli-build-prod-typeerror-cannot-read-property-kind-of-undefined

I can reopen if we find out I'm wrong
